### ISSUE TITLE
Remove usage of bintray

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/marketplace-utilities#6]
Bintray/Jcenter will be shut down https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

it is used here https://github.com/jboss-fuse/marketplace-utilities/blob/5aac96ce0c6a24ca4dec4aa864bc2d2786775fab/pom.xml#L62

for reference https://issues.redhat.com/browse/ENTESB-16031

**Comment by mmuzikar** [comment]
#8 closed this issue
